const Pages = {
    today() { return UI.todayPage(); },
    identity() { return `<div class="container"><div class="hero"><p class="greeting">${Helpers.greeting()}</p><h1 class="headline">Become</h1><p class="daily-quote">Who you are becoming shapes what you do.</p></div>${UI.identityDashboard()}</div>${UI.bottomNav("identity")}`; },
    more() { return `<div class="container"><div class="hero"><p class="greeting">Settings</p><h1 class="headline">More</h1><p class="daily-quote">Manage your account and preferences.</p></div><div class="stat-card"><h3>Account</h3><p>Signed in as:<br>${State.userEmail || ""}</p></div><div class="stat-card"><h3>Timezone</h3><p>Current: ${State.userTimezone || "Auto-detected"}</p><button class="btn btn-secondary" onclick="App.openTimezoneSettings()">Change Timezone</button></div><div class="stat-card"><h3>Data</h3><button class="btn btn-secondary" onclick="App.exportData()">Export Data</button><button class="btn btn-danger" onclick="App.confirmDeleteAccount()">Delete Account</button></div><button class="btn btn-danger" onclick="App.logout()">Logout</button></div>${UI.bottomNav("more")}`; },
    journal() { const today = Helpers.todayISO(); const reflection = State.reflections.find(r => r.reflection_date === today && r.identity_id === State.currentIdentityId); return `<div class="container"><div class="hero"><p class="greeting">${Helpers.greeting()}</p><h1 class="headline">Diary</h1><p class="daily-quote">Reflect on today's wins and challenges.</p></div>${reflection ? `<div class="stat-card"><h3>Today's Reflection</h3><div class="journal-card"><label>Win</label><textarea name="win" rows="2">${Helpers.escapeHtml(reflection.win || '')}</textarea></div><div class="journal-card"><label>Challenge</label><textarea name="challenge" rows="2">${Helpers.escapeHtml(reflection.challenge || '')}</textarea></div><div class="journal-card"><label>Tomorrow</label><textarea name="tomorrow" rows="2">${Helpers.escapeHtml(reflection.tomorrow || '')}</textarea></div><button class="btn btn-primary" onclick="App.saveReflection(event)">Save Reflection</button></div>` : `<div class="stat-card"><h3>Write Your Reflection</h3><form onsubmit="App.saveReflection(event)"><div class="journal-card"><label>Win</label><textarea name="win" rows="2" placeholder="What went well today?"></textarea></div><div class="journal-card"><label>Challenge</label><textarea name="challenge" rows="2" placeholder="What got in the way?"></textarea></div><div class="journal-card"><label>Tomorrow</label><textarea name="tomorrow" rows="2" placeholder="What's your plan for tomorrow?"></textarea></div><button class="btn btn-primary" type="submit">Save Reflection</button></form></div>`}${reflection ? `<div class="stat-card"><h3>Previous Reflections</h3>${UI.reflectionHistory()}</div>` : ''}</div>${UI.bottomNav("journal")}`; },
    calendar() { return `<div class="container"><div class="hero"><h1 class="headline">Your Progress</h1><p class="daily-quote">Consistency creates identity.</p></div>${UI.stats()}${UI.calendar()}${UI.sectionHeader("History")}${UI.historyTimeline()}</div>${UI.bottomNav("calendar")}`; },
    learn() { const completed = (State.lessonProgress || []).map(p => p.lesson_id); const total = Lessons.length; const progress = total === 0 ? 0 : Math.round((completed.length / total) * 100); const nextLesson = Lessons.find(l => !completed.includes(l.id)); const modules = [...new Set(Lessons.map(l => l.module))]; return `<div class="container"><div class="hero"><p class="greeting">Atomic Habits Training</p><h1 class="headline">Build better systems.</h1><p class="daily-quote">Small changes create remarkable results.</p></div><div class="stat-card"><h3>Learning Progress</h3><strong>${completed.length}/${total}</strong><p>${progress}% completed</p></div>${nextLesson ? `<div class="stat-card"><h3>Continue Learning</h3><p>Next: ${nextLesson.title}</p><button class="btn btn-primary" onclick="App.openLesson(${nextLesson.id})">Continue Lesson</button></div>` : `<div class="stat-card"><h3>Course Complete</h3><p>You completed all ${total} lessons.</p></div>`}${modules.map(module => `<div class="stat-card"><h3>${module}</h3>${Lessons.filter(l => l.module === module).map(lesson => { const unlocked = lesson.id === 1 || completed.includes(lesson.id) || completed.includes(lesson.id - 1); return `<div class="journal-card"><h3>${lesson.id}. ${lesson.title}</h3><p>${Helpers.escapeHtml(lesson.principle)}</p><p><strong>Challenge:</strong> ${Helpers.escapeHtml(lesson.action)}</p><button class="${completed.includes(lesson.id) ? "btn btn-secondary" : unlocked ? "btn btn-primary" : "disabled-button"}" onclick="${unlocked ? `App.openLesson(${lesson.id})` : ""}" ${unlocked ? "" : "disabled"}>${completed.includes(lesson.id) ? "Review Lesson" : unlocked ? "Start Lesson" : "Locked"}</button></div>`; }).join("")}</div>`).join("")}${UI.bottomNav("learn")}`; },
    weeklyReview() { return UI.weeklyReview(); },
    onboarding() { return UI.onboarding(); }
};
window.Pages = Pages;
